[project]
name = "ue-editor-mcpserver"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [				
    "mcp>=1.5.0",
    "anyio",
    "click",
    "starlette",
    "pywin32"
    ]
